name: Node.js CI

on:
  push:

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [ 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: INstall Yarn
      run: npm install -g yarn
    - name: Install deps
      run: |
        yarn install
        yarn electron:build
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist_electron/*.exe
